import { LocalBusiness } from './LocalBusinessCard'

export const localBusinesses: LocalBusiness[] = [
  {
    id: 1,
    name: '아속 힐링 마사지',
    category: '마사지',
    region: '방콕',
    address: '아속역 3분, Sukhumvit Soi 23',
    priceRange: '300~500 THB',
    description: '태국 전통 마사지와 아로마 오일 마사지 전문점. 한국어 소통 가능한 직원 상주. 깨끗하고 조용한 분위기.',
    discount: '태자 회원 20% 할인',
    isRecommended: true,
    hasDiscount: true,
    emoji: '💆',
    phone: '+66-2-123-4567',
    lineId: '@asok-healing',
    mapUrl: 'https://maps.google.com/?q=Sukhumvit+Soi+23+Bangkok',
    tags: ['한국어 가능', '깨끗함', '예약 가능', '주차 가능'],
  },
  {
    id: 2,
    name: '반쿤매 (Ban Khun Mae)',
    category: '맛집',
    region: '방콕',
    address: '시암역 도보 5분, Siam Square Soi 8',
    priceRange: '200~400 THB',
    description: '현지인도 줄 서서 먹는 정통 태국 가정식 레스토랑. 쏨땀, 팟타이, 똠양꿍이 특히 인기.',
    discount: '태자 회원 10% 할인',
    isRecommended: true,
    hasDiscount: true,
    emoji: '🍛',
    phone: '+66-2-234-5678',
    lineId: '@bankhunmae',
    mapUrl: 'https://maps.google.com/?q=Siam+Square+Soi+8+Bangkok',
    tags: ['현지 인기', '가정식', '태국 전통', '시암역'],
  },
  {
    id: 3,
    name: '텍사스 무까따 뷔페',
    category: '무까따',
    region: '방콕',
    address: '라차다 나이트마켓 근처, Ratchadaphisek Rd',
    priceRange: '199~299 THB',
    description: '무한리필 무까따 뷔페. 소고기, 돼지고기, 해산물 포함. 에어컨 좌석 있음. 소스 바 별도.',
    discount: '태자 회원 무료 음료 1잔',
    isRecommended: false,
    hasDiscount: true,
    emoji: '🥘',
    phone: '+66-2-345-6789',
    lineId: '@texas-mookata',
    mapUrl: 'https://maps.google.com/?q=Ratchadaphisek+Road+Bangkok',
    tags: ['뷔페', '무한리필', '에어컨', '주차 가능'],
  },
  {
    id: 4,
    name: '카페 드 방콕',
    category: '카페',
    region: '방콕',
    address: '통로 소이 13, Thonglor Soi 13',
    priceRange: '80~200 THB',
    description: '인스타 감성 브런치 카페. 수제 케이크와 스페셜티 커피가 유명. 작업하기 좋은 분위기.',
    isRecommended: true,
    hasDiscount: false,
    emoji: '☕',
    phone: '+66-2-456-7890',
    lineId: '@cafe-de-bkk',
    mapUrl: 'https://maps.google.com/?q=Thonglor+Soi+13+Bangkok',
    tags: ['브런치', '작업 가능', '인스타 감성', '통로'],
  },
  {
    id: 5,
    name: '파타야 릴렉스 스파',
    category: '마사지',
    region: '파타야',
    address: '센트럴 파타야, 2nd Road',
    priceRange: '250~600 THB',
    description: '파타야 최고 가성비 스파. 풋 마사지부터 풀 패키지까지. 커플 룸 보유.',
    discount: '태자 회원 15% 할인',
    isRecommended: false,
    hasDiscount: true,
    emoji: '🧖',
    phone: '+66-38-123-456',
    lineId: '@pattaya-relax',
    mapUrl: 'https://maps.google.com/?q=Central+Pattaya+2nd+Road',
    tags: ['커플 룸', '풀 패키지', '가성비', '센트럴 파타야'],
  },
  {
    id: 6,
    name: '아리 세탁 & 수선',
    category: '서비스',
    region: '방콕',
    address: '아리역 1번 출구, Phahon Yothin Soi 7',
    priceRange: '50~300 THB',
    description: '한인 운영 세탁 & 수선 전문점. 양복 수선, 드라이클리닝, 당일 세탁 가능. 카카오톡 문의 가능.',
    discount: '태자 회원 첫 이용 30% 할인',
    isRecommended: true,
    hasDiscount: true,
    emoji: '👔',
    phone: '+66-2-567-8901',
    lineId: '@ari-laundry',
    mapUrl: 'https://maps.google.com/?q=Phahon+Yothin+Soi+7+Bangkok',
    tags: ['한인 운영', '당일 세탁', '양복 수선', '아리역'],
  },
  {
    id: 7,
    name: '치앙마이 카오소이 쿤야이',
    category: '맛집',
    region: '치앙마이',
    address: '올드타운 내, Ratchamankha Rd',
    priceRange: '60~150 THB',
    description: '치앙마이 현지인 맛집 1위. 카오소이가 일품이며, 사떼도 꼭 드셔보세요. 오전에 방문 추천.',
    isRecommended: true,
    hasDiscount: false,
    emoji: '🍜',
    phone: '+66-53-123-456',
    mapUrl: 'https://maps.google.com/?q=Ratchamankha+Road+Chiang+Mai',
    tags: ['카오소이', '현지 1위', '오전 추천', '올드타운'],
  },
  {
    id: 8,
    name: '푸켓 선셋 카페',
    category: '카페',
    region: '푸켓',
    address: '까론 비치, Karon Beach Rd',
    priceRange: '100~250 THB',
    description: '까론 비치 오션뷰 카페. 선셋 시간대에 방문하면 최고. 시그니처 코코넛 스무디 추천.',
    discount: '태자 회원 음료 1+1',
    isRecommended: false,
    hasDiscount: true,
    emoji: '🌅',
    phone: '+66-76-234-567',
    lineId: '@phuket-sunset',
    mapUrl: 'https://maps.google.com/?q=Karon+Beach+Phuket',
    tags: ['오션뷰', '선셋', '코코넛 스무디', '까론 비치'],
  },
]
